### ISSUE TITLE
CMAP non existent key

### ISSUE THREAD

**Issue by roysiu-gh** [roysiu-gh/DDPM-HL-LHC#4]
E.g. plot jet 13

Traceback (most recent call last):
  File "/home/physics/phuqza/E9/DDPM-HL-LHC/./src/main.py", line 101, in <module>
    plot_detections(
  File "/home/physics/phuqza/E9/DDPM-HL-LHC/src/visualisation.py", line 137, in plot_detections
    colour = GLOBAL_CMAP[abs_pid]
KeyError: np.float64(13.0)

**Comment by roysiu-gh** [comment]
Fixed
